### ISSUE TITLE
Creation of molecule for ORF flow and Login

### ISSUE THREAD

**Issue by TheNPDev** [SamagraX-Stencil/stencil-mobile#2]
- [x] Reading Passage molecule
- [x] Result Screen molecule
- [x] Integration of BSTT player
- [x] Mobile/Aadhar Input Atom
- [x] Dynamic OTP Input Atom
- [x] Login Molecule

**Comment by AakashSatpute119** [comment]
- stencil molecules tobe added with BSTT player

**Comment by TheNPDev** [comment]
**Molecules for ORF flow:** 

I have completed the development of two new molecules for the ORF flow:

**1. PassageDisplayMolecule:** 
       This molecule is designed to display a passage with a progress line, text, and an image positioned at the bottom. This molecule can be 
       reused across different parts of the app where we need to present text along with an image at the bottom.

**2. CustomScreenMolecule:**
       This molecule is implemented to be used in multiple contexts within the app. Specifically, it is suitable for the following 
       screens:

- **Result Screen** of the ORF flow
- **Timeout Screen** of the ORF flow
- **Instructions Screen**

**Comment by charanpreet-s** [comment]
Merged with Nisai build
