### ISSUE TITLE
Android - App redesign (Stencil migration)

### ISSUE THREAD

**Issue by TheNPDev** [SamagraX-Stencil/stencil-mobile#5]
- [x] Redesigning of Login and OTP screen
- [ ] Development of ProfileMolecule
- [x] Integration of molecule on Home screen
- [ ] Integration of molecule on Student screen

## Login 

- [x] Login molecule
- [x] Integration of Molecule on screen

Effort - 1 day

## Home

- [x] Profile card molecule 
- [x] Samwad entry point
- [x] Class performance 
- [x] Room db tables and api integration
- [ ] Offline handling
- [x] Viewmodel and functionality setup

Effort - 3 days

## Student Profile

- [x] Card List Molecule
- [x] Profile card molecule
- [x] Graph stats for Nipun and Non-Nipun
- [x] Previous results with card list molecule
- [x] Room db tables and api integration
- [x] Offline handling
- [x] Viewmodel and functionality setup

Effort - 3 days

## Result

- [x] Nipun status with offline screen changes
- [x] Result with card molecule

Effort - 2 days

**Comment by karntrehan** [comment]
Blocked on https://github.com/NipunSahAIyak/android-nisai-orchestrator/issues/12

**Comment by dhruv-1001** [comment]
@TheNPDev to update progress on ticket.

**Comment by charanpreet-s** [comment]
To start with student details screen. @charanpreet-s to review card molecule

**Comment by dhruv-1001** [comment]
WIP Student Detail Page API Integration.

**Comment by charanpreet-s** [comment]
WIP Student detail completed, working on pagination and offline of student details @TheNPDev

**Comment by VargishChauhan** [comment]
Home page items done, review in progress.
Result page to be completed by 26 Aug,24

**Comment by AakashSatpute119** [comment]
- WIP

**Comment by charanpreet-s** [comment]
Dev Done, Feedback fixes in progress

**Comment by dhruv-1001** [comment]
Feedback fixes WIP.

**Comment by dhruv-1001** [comment]
Review in-progress. 
@VargishChauhan to provide update on design feedback

**Comment by TheNPDev** [comment]
@AakashSatpute119 
Build : https://drive.google.com/file/d/12jCc4h4MUKAWyYSTBgk45sEd5OSWiUYO/view?usp=sharing

Changes:

- New designs: Designs: https://www.figma.com/design/viU7EdVpIDwmq38uWMgxC2/Nipun-Bharat-AI?node-id=44-2399&t=cL4apwXTui79ISgm-0
- New Login and OTP screen
- New Home Screen for all the actors
- New Assessment Summary on the home screen with new api "assessment-summary"
- Student details screen on clicking the card of student in Teachers and Mentors from api "student-assessment-history"
- New Result screen with the expanded result only for BSTT result
- Offline handling of all the flow of taking assessment, updating student details screen and assessment summary on home page
cc: @charanpreet-s

**Comment by dhruv-1001** [comment]
@TheNPDev to update build with bstt flow.

**Comment by AakashSatpute119** [comment]
### Bugs : 

- [x] 1. [Teacher flow]: The assessment Summary on the home screen shows an incorrect count of nipun students for grade 2-3 stats. https://drive.google.com/file/d/1KSfv7YGK8X6PxYEHFxf-_nujIXFQZN0-/view?usp=sharing on Ajay

- [x] 2. [Teacher flow]: Showing duplicate buttons sometime in the hamburger menu. https://prnt.sc/HPJPu6cinQGp - Fixed

- [x] 3. [Teacher flow]: Competency detail shows blank after taping on student-assessed detail. ( In विद्यार्थी प्रमाण पत्र)   https://prnt.sc/aM5I-iJDoAU7 @charanpreet-s to be check

- [x] 4. Parent flow is missing as per design : current> https://prnt.sc/gCJ2cO6Eqvaq,Figma > https://www.figma.com/design/viU7EdVpIDwmq38uWMgxC2/Nipun-Bharat-AI?node-id=239-3220&t=PBTWBVa9eBdVIrD3-4 - Flow deprecated

- [x] 5. [Teacher flow]: The app crashes on the result screen while taking the assessment for an anonymous student.  https://drive.google.com/file/d/1KhOSBE_XMr49tVTqH93hPtCphglhvDl0/view?usp=sharing - Fixed

- [x] 6. [Teacher flow]: App crashes on the student result screen. A scenario where 2 teachers on the same school udise = 9150202302 and if logging in with 8668727053 number and taking assessment works fine but if I logged in with 2nd teacher (9999999991) on the same school. (both no have default otp) > https://drive.google.com/file/d/1KsOz9RS7OgVCs7O7cP-I5YEsx64P0I5i/view?usp=sharing - On Ajay

- [x] 7. Verify otp should have a timer for resending otp (Like current NL app), currently button is enabled for resending otp and clicking on it gives a message "Please try again later (in Hindi)": https://drive.google.com/file/d/1Kvl722H4JnwjmM4vcJzEgnA95OVyclkN/view?usp=sharing  - Fixed

- [x] 8. Auto-read OTP is not working. > https://drive.google.com/file/d/1L0HSkzyT6aMthqzn6EF4w1p6Man6G998/view?usp=sharing - @charanpreet-s to be check

- [x] 9. On the verify OTP page submit text should be in Hindi as per design - " दर्ज  करे " https://prnt.sc/x485vKh-zEYu - Fixed

- [x] 10. 0 students are assessed still showing gold batch on profile page.(creds - 9998887775 default otp)
 https://prnt.sc/Gej3yq3b2YDZ - Ajay to remove badges from api

- [x] 11. [Teacher/Diet mentor]The app crashes on the result screen for every assessment. (creds - 9998887775 -teacher/ 9998887774-diet mentor > default otp) > https://drive.google.com/file/d/1L5jf3J1Vx_thHVeOS1LotoAB8r5bSEs4/view?usp=sharing - On Ajay

- [x] 12. Why आकलन सारांश button is there in the mentor examiner flow?  https://prnt.sc/qOSdiAAogfez - Fixed

- [x] 13. App crashes on submit otp > https://go.screenpal.com/watch/cZQlIBVR858

- [x]  14. Minor UI fixes 1. Grade tab borders 2. Month change arrows. >> https://prnt.sc/LK3rYoIDTD6Y

**User POV**
- [ ]  1. The Vidhyarthi Akalan button should be on the right side also icons are not meaningful. https://prnt.sc/8qWDdtkKpaxU - On Vargish

**Comment by TheNPDev** [comment]
@AakashSatpute119 
Build: https://drive.google.com/file/d/12stFjvo_x3IXM0mGqj4jhDIgRARVkLsT/view?usp=sharing

cc: @charanpreet-s @karntrehan

**Comment by VargishChauhan** [comment]
1. The Vidhyarthi Akalan button should be on the right side also icons are not meaningful. https://prnt.sc/8qWDdtkKpaxU - On Vargish

For the above, will schedule a call with design team to help us out on this

**Comment by karntrehan** [comment]
Call with Design setup for tomorrow.

**Comment by dhruv-1001** [comment]
@TheNPDev to add design ticket link.

**Comment by TheNPDev** [comment]
Ticket to update Phase 1 after design changes: https://github.com/orgs/NipunSahAIyak/projects/1/views/2?pane=issue&itemId=79869386

**Comment by dhruv-1001** [comment]
Phase 1 tested. Ready to be deployed.
