### ISSUE TITLE
Android - Stencil migration - Phase 2 - Mentor Flow

### ISSUE THREAD

**Issue by TheNPDev** [SamagraX-Stencil/stencil-mobile#6]
## Mentor Home 
- [x] Add mentor data in home page API. (Ref: https://github.com/NipunSahAIyak/web-orchestrator/issues/57#issuecomment-2376693136)
- [x] Offline handling.

## Student selection

- [x] Search bar and filter buttons
- [x] Nipun count stats
- [x] Card Molecule
- [x] Students list
- [x] Integration with Room db

Effort - 3 days

## School Selection Screen

- [x] Search filter on udise/school name
- [x] district filter
- [x] Block filter
- [x] New School list molecule
- [x] Integration of School list molecule
- [x] Combine VM for Mentor and Examiner
- [x] Offline handling of entire flow

Effort - 3.5 days

## Enhancements

- [ ] RCT implementation on Home screen
- [x] Add Student Details on Result page
- [x] Changes of button on home screen
- [ ] Empty data of Assessment Summary scenario

Effort - 2 days

**Comment by dhruv-1001** [comment]
Waiting on design update.

**Comment by dhruv-1001** [comment]
@TheNPDev to combine https://github.com/SamagraX-Stencil/stencil-mobile/issues/7 with this ticket.

**Comment by AakashSatpute119** [comment]
**BUGs :**

- [x] 1. The examiner is able to submit more than 2 assessments when submitting assessments back to back without taking back to the examiner's home page.  https://drive.google.com/file/d/1IhjsPgUjJVuCrkFw4wrWPGfcEKOIS2XF/view?usp=sharing

- [x] 2. The Examiner is able to submit more than 2 assessments when he takes 2 assessments, logs out, and religions again https://drive.google.com/file/d/1IiKgUwLmOqQueNq6v7l5vJI0Z4iSnTId/view?usp=sharing

- [ ] 3. Unable to report school fraud API is returning` "status": false,"message": "School has not been accessed by you, in this assessment cycle."` a scenario where school assessments take 1-2min in a queue and we try to report that school. 

- [x] 4. Data sync with the worker not working. 

- [x] 5. Getting not nipun status on school listing page and school score card when one out grade has 0 students.(Offline scenario: where only grades 2 and 3 have students and both grades are nipun still shows notnipun) 
https://go.screenpal.com/watch/cZQD6MVSfpj - fixed on result page but still getting not nipun on school listing page

- [x] 6. The school scorecard is not showing after-school assessment data synced with the server. A case where one of the grades has 0 students. 
   https://go.screenpal.com/watch/cZQDXnVSf5b

**Mentor Bugs**

- [ ] 7. Chat is not working. https://go.screenpal.com/watch/cZ6efvVWccx 

- [ ] 8. The app crashes on the result screen when the app is offline. https://go.screenpal.com/watch/cZ6efJVWcny 

- [ ] 9.  After the app crashes on the result page in an offline state, if the user come on back and try to take another assessment  gets this message- "assessment not configured yet"  https://go.screenpal.com/watch/cZ6efKVWcn9 

- [ ] 10. On the school listing page whole school card should be clickable if I click on visited, not visited it's not working.

https://go.screenpal.com/watch/cZ6efMVWceF 

- refresh student on student list ? 
- grade wise stats for mentor ?

**Comment by dhruv-1001** [comment]
Ajay to connect with @dhruv-1001 on 3rd Bug point.

**Comment by AakashSatpute119** [comment]
Teacher flow stencil build : https://drive.google.com/file/d/13BzzGQLPb2UTUHLL3EE-exQsT4wXZ9E6/view

**Comment by karntrehan** [comment]
Mentor home page API changes done. Online flows can be tested right away. @TheNPDev to share online build right away. Offline support to be added and shared by EOD today.

**Comment by Ajay-Maury** [comment]
PR:- https://github.com/Mission-Prerna/nl-apis/pull/293  Deployed on stag to unblock FE.

- Cache not implemented on this API yet.
- Do we also need any grade-wise assessment data for Mentor?

### Mentor Assessment summary proposed response changed:-
```
{
    "month": 9,
    "year": 2024,
    "month_label": "सितंबर",
    "label": "आँकलन सारांश",
    "data": [
        {
            "cards": [
                {
                    "identifier": "currentMonthAssessments",
                    "label": "वर्तमान माह आँकलन",
                    "type": "metric",
                    "updated_at": 1727444753647,
                    "assessments_count": 166,
                    "data": [
                        {
                            "identifier": "assessedSchools",
                            "text": "विद्यालय के आँकलन पूरे किये ",
                            "count": 20
                        },
                        {
                            "identifier": "assessedStudents",
                            "text": "छात्रों के आँकलन पूरे किये",
                            "count": 45
                        },
                        {
                            "identifier": "assessmentMinutes",
                            "text": "औसत समय प्रति आँकलन",
                            "count": 4
                        }
                    ],
                    "metadata": {
                        "student_ids": [
                            "41067812",
                            "41069026",
                            ......................
                            "39582908",
                            "39820679"
                        ],
                        "school_udise": [
                            9150200805,
                            9150201201,
                            9150201401,
                           ...............................
                            9150209901
                        ]
                    }
                },
                {
                    "identifier": "lastMonthAssessments",
                    "label": "पिछला महीना आँकलन",
                    "type": "metric",
                    "updated_at": 1724918106367,
                    "assessments_count": 240,
                    "data": [
                        {
                            "identifier": "assessedSchools",
                            "text": "विद्यालय के आँकलन पूरे किये ",
                            "count": 6
                        },
                        {
                            "identifier": "assessedStudents",
                            "text": "छात्रों के आँकलन पूरे किये",
                            "count": 58
                        },
                        {
                            "identifier": "assessmentMinutes",
                            "text": "औसत समय प्रति आँकलन",
                            "count": 11
                        }
                    ],
                    "metadata": {
                        "student_ids": [
                            "41067812",
                            "41654191",
                              .......
                              .......
                            "41736139",
                        ],
                        "school_udise": [
                            9150200805,
                            9150202302,
                            9150204701,
                            9150204901,
                            9150205303,
                            9150206201
                        ]
                    }
                }
            ]
        }
    ]
}
```

**Comment by TheNPDev** [comment]
@AakashSatpute119 
Build with online working of Mentor Flow on Home screen: https://drive.google.com/file/d/13D3c7txcKrM73Df5Ixrt4ELgTvjVqNOq/view?usp=sharing
cc: @karntrehan @charanpreet-s

**Comment by dhruv-1001** [comment]
@TheNPDev to share current build.

**Comment by karntrehan** [comment]
Deprioritised.
