### ISSUE TITLE
Add on changes in App Redesign Phase 1

### ISSUE THREAD

**Issue by TheNPDev** [SamagraX-Stencil/stencil-mobile#7]
- [ ] Sos feature on Home screen
- [ ] RCT implementation on Home screen
- [ ] Add Student Details on Result page
- [ ] Changes of button on home screen
- [ ] Empty data of Assessment Summary scenario

**Comment by karntrehan** [comment]
Vargish to review.

**Comment by karntrehan** [comment]
Moved to #6
