### ISSUE TITLE
[Android] Stencil Phase 3 - Examiner Flows

### ISSUE THREAD

**Issue by karntrehan** [SamagraX-Stencil/stencil-mobile#8]
## Student  Selection Screen

- [ ] Anomaly Handling
- [ ] Image Capturing
- [ ] Audio Mascot
- [ ] Nipun count stats (New feature in School screen)
- [ ] Combining Viewmodel's fun

## School Selection Screen
- [ ] Sos feature handling

## Enhancements
- [ ] Sos feature on Home screen

**Comment by vishalmaurya850** [comment]
Can I get the design ideas so that I can help you in designing the app

**Comment by karntrehan** [comment]
Deprioritised.
